name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main  # Asegúrate de que coincida con tu rama principal
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install && npm run build  # Ajusta según tu framework (ej: React/Vue)
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseToken: ${{ secrets.FIREBASE_TOKEN }}  # Usa el token aquí
          projectId: autogestionpro